defmodule DxCore.Agents.Web.Endpoint do
  use Phoenix.Endpoint, otp_app: :dxcore_coordinator_oss

  # check_origin disabled: agents connect via Tailscale IP, not a hostname
  socket "/agent", DxCore.Agents.Web.AgentSocket,
    websocket: [check_origin: false],
    longpoll: false

  socket "/dispatcher", DxCore.Agents.Web.DispatcherSocket,
    websocket: [check_origin: false],
    longpoll: false

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_dxcore_agents_key",
    signing_salt: "D/smMsMX",
    same_site: "Lax"
  ]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :dxcore_coordinator_oss,
    gzip: not code_reloading?,
    only: DxCore.Agents.Web.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug DxCore.Agents.Web.Router
end
